import os
import json


def save_html_report(results, model_name, output_dir="results"):
    """Generate an HTML dashboard from benchmark results."""
    os.makedirs(output_dir, exist_ok=True)

    rows = ""
    for r in results:
        lat = r["latency"]
        params = f"{r.get('param_count', 0):,}"
        rows += (
            "<tr>"
            f"<td>{r['backend']}</td>"
            f"<td>{params}</td>"
            f"<td>{r.get('model_size_mb', '-')}</td>"
            f"<td>{r.get('disk_size_mb', '-')}</td>"
            f"<td>{lat['p50_ms']}</td>"
            f"<td>{lat['p95_ms']}</td>"
            f"<td>{lat['p99_ms']}</td>"
            f"<td>{r['peak_memory_mb']}</td>"
            f"<td>{r['throughput_ops_sec']}</td>"
            "</tr>\n"
        )

    bar_data = json.dumps([
        {"backend": r["backend"], "p50": r["latency"]["p50_ms"]}
        for r in results
    ])

    size_data = json.dumps([
        {"backend": r["backend"], "size": r.get("model_size_mb", 0)}
        for r in results
    ])

    css = (
        "body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; background: #0f0f0f; color: #e0e0e0; }\n"
        "h1 { color: #00c896; }\n"
        "h2 { color: #aaa; margin-top: 32px; }\n"
        "table { border-collapse: collapse; width: 100%; margin-top: 16px; }\n"
        "th, td { border: 1px solid #333; padding: 10px 14px; text-align: right; }\n"
        "th { background: #1a1a1a; color: #00c896; text-align: center; }\n"
        "td:first-child, th:first-child { text-align: left; }\n"
        "tr:nth-child(even) { background: #1a1a1a; }\n"
        ".charts { display: flex; gap: 48px; flex-wrap: wrap; }\n"
        ".chart-container { margin-top: 24px; display: flex; align-items: flex-end; gap: 24px; height: 220px; padding: 16px; }\n"
        ".chart-section { flex: 1; min-width: 280px; }\n"
        ".bar-group { display: flex; flex-direction: column; align-items: center; }\n"
        ".bar { width: 64px; border-radius: 4px 4px 0 0; }\n"
        ".bar-latency { background: #00c896; }\n"
        ".bar-size { background: #4a9eff; }\n"
        ".bar-label { margin-top: 8px; font-size: 13px; }\n"
        ".bar-value { font-size: 12px; color: #aaa; margin-bottom: 4px; }\n"
        ".footer { margin-top: 40px; color: #555; font-size: 13px; }\n"
    )

    script = (
        "function renderChart(containerId, data, key, unit, barClass) {\n"
        "    var maxVal = Math.max.apply(null, data.map(function(d) { return d[key]; }));\n"
        "    if (maxVal === 0) maxVal = 1;\n"
        "    var chart = document.getElementById(containerId);\n"
        "    if (!chart) return;\n"
        "    data.forEach(function(d) {\n"
        "        var h = Math.max((d[key] / maxVal) * 180, 4);\n"
        "        var div = document.createElement('div');\n"
        "        div.className = 'bar-group';\n"
        "        div.innerHTML = '<div class=\"bar-value\">' + d[key] + ' ' + unit + '</div>'\n"
        "            + '<div class=\"bar ' + barClass + '\" style=\"height:' + h + 'px\"></div>'\n"
        "            + '<div class=\"bar-label\">' + d.backend + '</div>';\n"
        "        chart.appendChild(div);\n"
        "    });\n"
        "}\n"
    )

    html = (
        "<!DOCTYPE html>\n"
        "<html lang='en'>\n"
        "<head>\n"
        "<meta charset='UTF-8'>\n"
        f"<title>ArmBench Report - {model_name}</title>\n"
        f"<style>\n{css}</style>\n"
        "</head>\n"
        "<body>\n"
        "<h1>ArmBench Report</h1>\n"
        f"<p>Model: <strong>{model_name}</strong></p>\n"
        "<h2>Results</h2>\n"
        "<table>\n"
        "<tr><th>Backend</th><th>Params</th><th>Size (MB)</th>"
        "<th>p50 (ms)</th><th>p95 (ms)</th><th>p99 (ms)</th>"
        "<th>Peak Mem (MB)</th><th>Throughput (ops/s)</th></tr>\n"
        f"{rows}"
        "</table>\n"
        "<div class='charts'>\n"
        "<div class='chart-section'>\n"
        "<h2>p50 Latency Comparison</h2>\n"
        "<div class='chart-container' id='latency-chart'></div>\n"
        "</div>\n"
        "<div class='chart-section'>\n"
        "<h2>Model Size Comparison</h2>\n"
        "<div class='chart-container' id='size-chart'></div>\n"
        "</div>\n"
        "</div>\n"
        "<div class='footer'>Generated by ArmBench</div>\n"
        "<script>\n"
        f"{script}\n"
        f"renderChart('latency-chart', {bar_data}, 'p50', 'ms', 'bar-latency');\n"
        f"renderChart('size-chart', {size_data}, 'size', 'MB', 'bar-size');\n"
        "</script>\n"
        "</body>\n"
        "</html>"
    )

    filepath = os.path.join(output_dir, f"{model_name}_report.html")
    with open(filepath, "w") as f:
        f.write(html)
    print(f"  Dashboard saved: {filepath}")
    return filepath